modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cascade_sorcery"
version="1.0.0"
displayName="Cascade Sorcery"
credits="Thank you to everyone who help with art and stuff for this mod"
displayURL="http://skynetcloud.xyz"
logoFile="logo.png"
authors="SkyNetCloud"

[[dependencies.cascade_sorcery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




