modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cascade_sorcery"
version="1.0.0"
displayName="Cascade Sorcery"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="black, MCreator"

[[dependencies.cascade_sorcery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




